version: '3'
services:
  app:
    image: app
    command: ["/usr/wait-for-it.sh", "db:5432", "-t", "30", "--", "java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - sevents-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: minhaSenha
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - sevents-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - sevents-network

networks:
  sevents-network:
    external: true