spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: minhaSenha
    driver-class-name: org.postgresql.Driver
  redis:
    host: redis
    port: 6379
server:
  port: 8080